services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command:
            - /bin/sh
            - -c
            - bash /start.sh
        ports:
            - 8080:8080
            - 8081:8081
            - 8082:8082